# Generated by Django 4.2.13 on 2026-03-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(blank=True, help_text='Twilio CallSid identifier', max_length=64)),
                ('caller', models.CharField(blank=True, help_text='Caller phone number', max_length=32)),
                ('user_query', models.TextField(help_text='What the caller asked')),
                ('ai_response', models.TextField(help_text='Response returned by the AI agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
