# Generated by Django 4.2.13 on 2026-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the property', max_length=255)),
                ('location', models.CharField(help_text='Area/city where the property is located', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (e.g. 7500000 for 75 lakh)', max_digits=12)),
                ('carpet_area', models.PositiveIntegerField(help_text='Carpet area in square feet')),
                ('bedrooms', models.PositiveSmallIntegerField(help_text='Number of bedrooms (BHK)')),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of amenities, e.g. ['swimming pool', 'gym', 'parking']")),
                ('description', models.TextField(blank=True, help_text='Detailed description of the property')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
